### ISSUE TITLE
NoneType with a feed

### ISSUE THREAD

**Issue by hamilkarbarkas** [manolomartinez/greg#50] opened 2016-05-27 11:56 UTC
Hey,

first of all thanks for the great tool.

With this feed:
[Latzel]
url = http://www.st-martini.net/rss/podcast/stm-predigten.xml
date_info = available

download with "greg download 1-315" works fine. However when trying "greg sync Latzel" greg returns:

Checking Latzel...
Traceback (most recent call last):
  File "/sw/bin/greg", line 9, in <module>
    load_entry_point('Greg==0.4.6', 'console_scripts', 'greg')()
  File "/sw/lib/python3.5/site-packages/greg/gregparser.py", line 118, in main
    function(vars(args))
  File "/sw/lib/python3.5/site-packages/greg/greg.py", line 768, in sync
    feed.fix_linkdate(entry)
  File "/sw/lib/python3.5/site-packages/greg/greg.py", line 261, in fix_linkdate
    entry.linkdate = list(entry.published_parsed)
TypeError: 'NoneType' object is not iterable

I use a Mac with python-pip 8.10 .

Any ideas?

Thanks in advance
Martin

[greg.conf.txt](https://github.com/manolomartinez/greg/files/286394/greg.conf.txt)

**Comment by manolomartinez** [comment] 2016-05-29 22:58
Hi, Martin,

Thanks for reporting. This should be fixed now at the tip of the repo. Let me know if it works.

Cheers,
Manolo

**Comment by hamilkarbarkas** [comment] 2016-06-19 10:49
thanks!

2016-05-30 0:58 GMT+02:00 manolomartinez <notifications@github.com>:

**Comment by manolomartinez** [comment] 2016-06-19 13:55
I assume this means the issue is solved; good! Closing for now, if it appears again let me know.

**Closed by manolomartinez** 2016-06-19 13:55 UTC
